feat(models): add User and Note type references
remix-run/grunge-stack pull request #22
Opened 2022-03-18 09:09 UTC by joematune

**tldr**: This PR includes semantic TS only changes

- Add type references between models - 470c91be42847daeba7eadd17806f560da841faf

Reasoning: As Dynamo models grow, the ability to add relations between models can be illustrated and documented with TS. This is especially true for single table design patterns as seen below where we can see that a note record's `pk` is a reference to the user's `id`, which is of type: `note#${string}`. The note's `id` on the other hand is a `cuid` which is documented with type `ReturnType<typeof cuid>`

![Screen Shot 2022-03-18 at 11 06 17](https://user-images.githubusercontent.com/44626877/158973286-6cd38104-aba5-4568-ab5c-b3330a38defb.png)
![Screen Shot 2022-03-18 at 11 06 45](https://user-images.githubusercontent.com/44626877/158973353-856f2cfd-d6da-47d1-9751-04187185b071.png)

2022-03-18 13:13 UTC, MichaelDeBoey requested changes

2022-03-18 13:13 UTC, MichaelDeBoey commented on app/models/note.server.ts
> +import { User } from "./user.server";
Since we're only using the type, let's import just the type

```suggestion

import type { User } from "./user.server";
```

2022-03-18 13:44 UTC, MichaelDeBoey approved these changes

2022-03-18 18:11 UTC, kentcdodds approved these changes
I'm a fan 👍

2022-03-18 18:16 UTC, kentcdodds commented
Could you take a look at the type errors in this PR?

2022-03-18 20:55 UTC, joematune commented
> Could you take a look at the type errors in this PR?

@kentcdodds Will squash them 👍

2022-03-19 07:34 UTC, joematune commented
@kentcdodds - Tidied the errors here - [aa57c40](https://github.com/remix-run/grunge-stack/pull/22/commits/aa57c401bb7dd57a34dcd5d2313b30edcd3c82b0)

I ran `npm run typecheck`, which was the point of failure in the [previous run of actions](https://github.com/remix-run/grunge-stack/runs/5604869869?check_suite_focus=true), and it came out clean. Should be solid this time 🙆

2022-03-19 13:16 UTC, kentcdodds approved these changes
Thank you 👏

2022-03-19 13:17 UTC, merged